### ISSUE TITLE
本地预览watch mip.js

### ISSUE THREAD

**Issue by wupengFEX** [mipengine/mip-cli#22]
目前来说没有watch mip.js，每当有变化的时候只能 `npm run dev` 手动编译，希望可以做成自动化的

**Comment by xuexb** [comment]
这是由于监听本地 MIP 核心仓库改动并自动编译逻辑在 `mip.config.livereload` 条件里面导致，代码： 
 https://github.com/mipengine/mip-cli/blob/v1.1.7/lib/server-start.js#L163-L171
