### ISSUE TITLE
Linux安装后 mip init，mip add 等命令不能使用

### ISSUE THREAD

**Issue by vivine** [mipengine/mip-cli#30]
查了一下原因，在linux里没有除了mip之外的其他命令，因为其他命令没有创建软链

https://github.com/mipengine/mip-cli/blob/ddacb026c9999594f2edec0ba7b87f73b64704a1/package.json#L6-L8

这里只创建了主命令mip的配置，应该加上其他命令的配置，大致如下：

```javascript
"bin": { 
   "mip": "bin/mip",
   "mip-init": "bin/mip-init",
   .......
 },
```
以上~~~~

**Comment by xuexb** [comment]
hi @vivine ，请问你说的不能使用的命令是不是指：

```
mip-add - 不能用
mip add - 可以用
```

这样吗？

**Comment by vivine** [comment]
只有mip能用，其余的命令都不好使

**Comment by xuexb** [comment]
hi @vivine ，根据文档提示：

``` bash
# 在当前项目创建一个mip模板网页：
mip add index.html [mip-xxx...]

# 创建一个mip组件：
mip addelement mip-demo

# 验证mip网页：
mip validate index.html [...]

# 启动本地网页调试服务
mip server
```

等命令，可使用 `mip --help` 查看更多命令帮助。

使用的是 `commander` 模块的子命令功能，文档见：
 <https://www.npmjs.com/package/commander#git-style-sub-commands>

**Comment by vivine** [comment]
问题是这样的哈：
package.json 里边的  bin  主要是用来配置全局命令的，当安装的时候（假设node安装目录为 `node`），会在 `node/bin` 下面创建一个软链 mip 并且指向 node 安装目录下面 `node/lib/node_modules/mip-cli/bin/mip`。此时 `mip` 这个命令可用。但是，其他命令 比如  `mip add`、`mip server` 等命令并没有在 `node/bin` 创建软链指向对应的执行程序， 所以其他命令在全局下面是不可以用的。

解决办法我猜测应该是在 package.json 的 bin 里边再加上类似下面的这种：
```javascript
"bin": { 
   "mip": "bin/mip",
   "mip-init": "bin/mip-init",
   .......
 },
```
这样的话就会自动创建软链了，而不是安装完后，还需要手动配置软链。下图中除了 mip 之外，其他都是我手动配置的 软链。

![rtx](https://user-images.githubusercontent.com/1614610/33793716-80ad7c38-dcf7-11e7-8dd3-b0cedc677e12.png)

**Comment by xuexb** [comment]
hi @vivine ， MIP 的 CLI 命令是通过 `mip command params` 执行的，而不是 `mip-command params` 哈~

**Comment by vivine** [comment]
我知道 MIP 的 cli 是通过 `mip command params` 来执行。

这样吧，我贴一个链接，也许比我表达的要清楚一些。http://www.cnblogs.com/wmhuang/p/7092658.html。

看了一下 package.json 里边 bin 的作用，觉得你们这个还是得按照我一楼说的那样改一下，才不用手动去配置符号链接（软链）

**Comment by xuexb** [comment]
@vivine  我明白你的意思，但 MIP 的 CLI 命令就是明确通过 `mip command params` ，不提供 `mip-command params` 形式的哈~ 所以没必要创建 `bin` 配置。

**Comment by vivine** [comment]
这样吧，你自己试着重新安装mip-cli，然后你全局执行一下mip add 会提示找不到该命令

**Comment by xuexb** [comment]
> 你自己试着重新安装mip-cli，然后你全局执行一下mip add 会提示找不到该命令

@vivine 我试过啊，没问题啊~ 并且我在新的 windows10 虚拟机里安装也正常~

你那里有问题吗？加下我q 463004799 我看下？或者你提供下你运行环境信息：

1. 系统名称和版本
2. nodejs 版本
3. 安装方式和对应版本，如：npm、yarn、cnpm等
1. 错误信息
