### ISSUE TITLE
我的组件在审核平台通过了,但是链接找不到文件

### ISSUE THREAD

**Issue by qz463390618** [mipengine/mip-cli#31]
如题,我自己写的组件审核通过了,然后平台不是有个线上地址吗,我点击,显示404页面,我html调用线上地址也没用

**Comment by xuexb** [comment]
hi @qz463390618 请发下你的组件名或者连接吧~

**Comment by qz463390618** [comment]
mip-judge-port       https://mipcache.bdstatic.com/extensions/platform/v1/mip-judge-port/mip-judge-port.js

**Comment by qz463390618** [comment]
@xuexb mip-judge-port https://mipcache.bdstatic.com/extensions/platform/v1/mip-judge-port/mip-judge-port.js
