### ISSUE TITLE
关于mip.config配置

### ISSUE THREAD

**Issue by jasonvanf** [mipengine/mip-cli#32]
您好，请问我在mip init等操作过后，开始mip server，然后点开index.html是一片空白，于是回过头来修改mip.config配置项中的mipDir，但是怎么配置都会报路径错误。
![6sc d7jv81h v 4 g g1](https://user-images.githubusercontent.com/24243477/33063163-a48722f4-cedc-11e7-86b6-d56caad8407b.png)
这是我初始化操作的目录不对还是配置的路径不对？请求帮助

**Comment by xuexb** [comment]
hi @JasonDurian 你是调试 MIP 组件吗？如果是，你可以在你你项目文件夹内使用 `mip addelement mip-demo` 创建对应的组件文件，再使用 `mip server` 启动本地开发预览。

而 `mip.config` 文件中 `mipDir` 字段配置是 [开发MIP框架](https://github.com/mipengine/mip-cli/wiki/%E8%B0%83%E8%AF%95mip%E6%A1%86%E6%9E%B6) 的。

**Comment by xuexb** [comment]
1. [MIP开发教程(二) 使用MIP-CLI工具调试MIP网页](http://www.cnblogs.com/mipengine/p/mip_cli_2_page.html)
1. [MIP开发教程(三) 使用MIP-CLI工具调试组件](http://www.cnblogs.com/mipengine/p/mip_cli_3_extension.html)

**Comment by jasonvanf** [comment]
感谢回答。
我是调试MIP组件，也使用  mip addelement mip-demo 创建了对应的组件文件。首先我的一个疑惑是mip init应该在组件文件夹内，还是上一级（也就是组件列表文件夹）；其次就是组件所需的js文件会在mip add的html文件中自动引用吗？

**Comment by jasonvanf** [comment]
已经按照上面的教程配置成功了，非常感谢，之前没有找到教程

**Comment by xuexb** [comment]
赞，希望下面的描述加深你的理解哈：

- MIP 组件调试 - 在组件目录执行的 `mip server` 命令，主要是使用 `README.md` 中的 代码片段完成各种状态下的组件开发，可参考 [mip-fixed 示例片段](https://raw.githubusercontent.com/mipengine/mip-extensions/master/src/mip-fixed/README.md) 。
- MIP 网页调试 - 用来结合真实网页数据调试页面，在你页面目录，初始化 `mip init` ，并配置 `extensionsDir` 路径为你组件的目录，执行 `mip add index.html mip-demo` 可创建对应的页面和对应引用的组件，而配置的 `extensionsDir` 字段是为了查找你开发的组件目录，也就是本地替换。如果说你开发的 MIP 页面依赖的组件全是线上的，你可以不用配置 `extensionsDir` 字段。

你的目录结构可以是这样（仅供参考）：

```
.
└── mip-repo                    - MIP 项目主目录
    ├── extensions              - MIP 组件目录
    │   └── mip-demo            - 本地组件目录
    │       ├── README.md
    │       ├── mip-demo.js
    │       ├── mip-demo.less
    │       └── package.json
    └── page                    - MIP 页面目录
        ├── index.html          - 调试组件页面，也就是真实的网页
        └── mip.config          - 配置文件
```

再有任何问题，欢迎再提 issue ~ 🍦
