### ISSUE TITLE
extensionsDir 本地组件是否存在检查

### ISSUE THREAD

**Issue by xuexb** [mipengine/mip-cli#33]
在 `mip.config` 文件中配置了 `extensionsDir` 为本地路径后，会替换 MIP 页面中的组件链接，但如果本地组件文件只是部分自己开发的，并没有覆盖全部组件，那么就会出现404。如：

页面加载了 `mip-share` 和 `mip-demo` 组件，而本地只有 `mip-demo` 我自己的组件， `mip-share` 本身我想加载线上官方的。

**Comment by xuexb** [comment]
@wupengFEX 看下这个问题，有2个派系：

- 正方 - 虽然配置了 `extensionsDir` ，但本地只是开发一个组件，而页面依赖多个组件，除了本地的组件外，其他组件就应该加载线上，这样才能保证稳定性。
- 反方 - 因为配置了 `extensionsDir` ，而这个配置就是本地化组件目录，已经明确配置了，那么就应该为配置买单。如果404，就手动把对应的组件 down 下来。（说的好像略2。。。）

**Comment by wupengFEX** [comment]
@xuexb 我觉得正方合理点，如果本地没有就不替换页面地址，这样也能保证页面正常运行

**Comment by xuexb** [comment]
ok，我也支持正方，这样也方便使用 cli 调试单个组件了，我升级下。
