### ISSUE TITLE
mip server成功，但是无法打开url

### ISSUE THREAD

**Issue by elang126** [mipengine/mip-cli#4]
已按文档步骤进行到最后一步，也成功mip server ，但是用浏览器打开http://127.0.0.1:8000或者本地的http：//172.xxx.xxx.xxx：8000或者http：//172.xxx.xxx.xxx：35730都不能打开？

**Comment by kekee000** [comment]
如果mip server启动没有报错，可能开了代理，或者8000端口被占用，换一个端口试下：

```
mip server -p 8001
```
