### ISSUE TITLE
Promise 不是这么写的...

### ISSUE THREAD

**Issue by 599316527** [mipengine/mip-cli#53]
https://github.com/mipengine/mip-cli/blob/5aa26c49f2fef3a5741728574bf720bce3eaa4b7/lib/mip-custom/custom-compile.js#L135-L145
用了等于白用~

![image](https://user-images.githubusercontent.com/1331413/43407263-d18422ae-9450-11e8-9ee4-3c0931803f18.png)

**Comment by Justineo** [comment]
这个直接 PR 吧

**Comment by 599316527** [comment]
怕是已经没人管了吧，我看 mip2 里面重写了一个 mip-cli

GU Yiling <notifications@github.com>于2018年7月31日 周二02:05写道：

**Comment by tayqassqan** [comment]
后续此部分功能整体迁移mip2 cli，在mip2 cli里解决
