### ISSUE TITLE
调试MIP 组件 无法读取READEME.md

### ISSUE THREAD

**Issue by qiuguanyou** [mipengine/mip-cli#8]
> 以下是我的操作步骤：

1. 在\mip-extensions 执行 mip init

2. 在\mip-extensions 执行 mip addelement mip-demo

3. 在\mip-extensions 执行 mip add index.html

4. 在\mip-extensions 执行 mip validate index.html 【验证成功】

5. 在\mip-extensions 执行 mip server

> 但并没有读取组件中的 \mip-extensions\mip-demo\READEME.md 文件 ，不知道是我的操作有误？  还是什么原因？求解，谢谢！

**Comment by kekee000** [comment]
mip-extensions 是组件仓库，会自动生成调试页面，无需手动添加index.html，直接在mip-extensions中启动`mip server`就可以看到组件列表了，点击任意组件可以进行单组件调试
顺序是：
```
mip addelement mip-demo
# 编写mip组件代码以及`README.md`文件
mip validateelement mip-demo
mip server
```
