### ISSUE TITLE
官方组件根本无法满足需求，却不允许提交自己的组件！！！！

### ISSUE THREAD

**Issue by zhurizhe** [mipengine/mip-cli#9]
官方的mip-nav-slidedown 菜单不能改样式，不能改按钮位置，提交了issue也不知道什么能更新，自己提交组件居然还说“该组件功能和官方提供的mip-accordion一致，可以通过官方组件实现”，我明明要实现的是类似mip-nav-slidedown功能，结果让我去使用mip-accordion，审核的人到底搞得清楚吗？官方组件就只会打回，也没有申诉和沟通的渠道，这到底算什么？

**Comment by cangku** [comment]
可以自己提交组件，但是不能重复功能性组件，业务组件支持提交，[在这里](https://github.com/mipengine/mip-extensions)。但是过程中还是有很多问题，我们的项目已经暂时暂停了，问题太多不好处理

**Comment by zhurizhe** [comment]
我也不想提交重复组件，但是指望官方更新，我不知道时间上能不能有保证，我们自己网站总不能把希望寄托在别人身上，请多理解。

**Comment by cangku** [comment]
理解，我也只是用户而已

**Comment by zhurizhe** [comment]
我还以为你是官方技术支持呢。。。。

**Comment by cangku** [comment]
只是我之前同样也因为这个问题关注过，所以有 email 提醒，感觉有同感，就回复你了
